### PR TITLE
Fix for issue #132

### PR DESCRIPTION
**Pull request by phprus**
Fix ```ghc::filesystem::remove_all``` behavior if argument is symlink (#132)
See https://en.cppreference.com/w/cpp/filesystem/remove:
> Symlinks are not followed (symlink is removed, not its target).

Update CI: Switch from ubuntu 16.04 to 18.04

### CODE REVIEW

**Comment by phprus** [comment]
@gulrak review my PR please.

**Comment by gulrak** [comment]
Sorry, I had some very busy weeks at my job. Thank you for this fix and for the CI update to 18.04!

**Comment by phprus** [comment]
I apologize for distracting you from your job.

**Comment by gulrak** [comment]
No, please, I'm happy you fixed it! No apologies needed, I plan to make a new release late (in CEST) on Sunday. Thanks for your supportive work!

**Pull request merged**
